### ISSUE TITLE
"Expected to decode String but found a dictionary instead."

### ISSUE THREAD

**Issue by KassBarraK** [DeveloperZelentsov/AiSwiftAssist#11]
it seems to me that there is an issue with the messagesApi.getMessages when the message contains annotations. (Generated when the assistant uses the "retrieval" tool to search files.)

typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "content", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "text", intValue: nil), CodingKeys(stringValue: "annotations", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "Expected to decode String but found a dictionary instead.", underlyingError: nil))

Shall we change the "public let annotations:[String]?" and consider that annotations is an array of File citation
object and File path object ?

**Comment by DeveloperZelentsov** [comment]
Thank you for bringing the issue with the _messagesApi.getMessages_ function to our attention. To help us better understand and resolve the problem, could you please provide us with the full JSON response where this error occurs? This information will be crucial in diagnosing and fixing the issue more effectively.

Thank you for your cooperation and assistance in improving our library.

**Comment by gustininho** [comment]
This is an issue which appears when assistant cites information from a file in the answer (with retrieval tool), please revise data model for this. Easy to reproduce. Thanks 🙏
